export const NODE_TYPES_CONFIG = {
  start: {
    label: 'Inicio',
    color: 'bg-emerald-500',
    border: 'border-emerald-500',
    textColor: 'text-emerald-400',
    bgLight: 'bg-emerald-500/10',
    icon: '▶',
    description: 'Punto de entrada del flujo',
    maxInputs: 0,
    maxOutputs: 1,
  },
  form: {
    label: 'Formulario',
    color: 'bg-blue-500',
    border: 'border-blue-500',
    textColor: 'text-blue-400',
    bgLight: 'bg-blue-500/10',
    icon: '📋',
    description: 'Recolecta datos del cliente',
    maxInputs: 1,
    maxOutputs: 1,
  },
  ai: {
    label: 'Análisis IA',
    color: 'bg-purple-500',
    border: 'border-purple-500',
    textColor: 'text-purple-400',
    bgLight: 'bg-purple-500/10',
    icon: '🤖',
    description: 'Analiza respuestas con IA',
    maxInputs: 1,
    maxOutputs: 1,
  },
  condition: {
    label: 'Condición',
    color: 'bg-yellow-500',
    border: 'border-yellow-500',
    textColor: 'text-yellow-400',
    bgLight: 'bg-yellow-500/10',
    icon: '◆',
    description: 'Bifurca el flujo según condición',
    maxInputs: 1,
    maxOutputs: 2,
  },
  notification: {
    label: 'Notificación',
    color: 'bg-orange-500',
    border: 'border-orange-500',
    textColor: 'text-orange-400',
    bgLight: 'bg-orange-500/10',
    icon: '🔔',
    description: 'Envía email o mensaje',
    maxInputs: 1,
    maxOutputs: 1,
  },
  end: {
    label: 'Fin',
    color: 'bg-red-500',
    border: 'border-red-500',
    textColor: 'text-red-400',
    bgLight: 'bg-red-500/10',
    icon: '⏹',
    description: 'Fin del flujo',
    maxInputs: 1,
    maxOutputs: 0,
  },
}
