export const NODE_TYPES_CONFIG = {
  start: {
    label: 'Inicio',
    color: 'bg-emerald-600',
    border: 'border-emerald-300',
    textColor: 'text-emerald-700',
    bgLight: 'bg-emerald-50',
    icon: '▶',
    description: 'Punto de entrada del flujo',
    maxInputs: 0,
    maxOutputs: 1,
  },
  form: {
    label: 'Formulario',
    color: 'bg-blue-700',
    border: 'border-blue-300',
    textColor: 'text-blue-800',
    bgLight: 'bg-blue-50',
    icon: '📋',
    description: 'Recolecta datos del cliente',
    maxInputs: 1,
    maxOutputs: 1,
  },
  ai: {
    label: 'Análisis IA',
    color: 'bg-violet-600',
    border: 'border-violet-300',
    textColor: 'text-violet-700',
    bgLight: 'bg-violet-50',
    icon: '🤖',
    description: 'Analiza respuestas con IA',
    maxInputs: 1,
    maxOutputs: 1,
  },
  condition: {
    label: 'Condición',
    color: 'bg-amber-600',
    border: 'border-amber-300',
    textColor: 'text-amber-700',
    bgLight: 'bg-amber-50',
    icon: '◆',
    description: 'Bifurca el flujo según condición',
    maxInputs: 1,
    maxOutputs: 2,
  },
  notification: {
    label: 'Notificación',
    color: 'bg-orange-600',
    border: 'border-orange-300',
    textColor: 'text-orange-700',
    bgLight: 'bg-orange-50',
    icon: '🔔',
    description: 'Envía email o mensaje',
    maxInputs: 1,
    maxOutputs: 1,
  },
  end: {
    label: 'Fin',
    color: 'bg-rose-600',
    border: 'border-rose-300',
    textColor: 'text-rose-700',
    bgLight: 'bg-rose-50',
    icon: '⏹',
    description: 'Fin del flujo',
    maxInputs: 1,
    maxOutputs: 0,
  },
}
